version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: tecnofit-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - tecnofit-network

  nginx:
    image: nginx:alpine
    container_name: tecnofit-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - tecnofit-network

  db:
    image: mysql:8.0
    container_name: tecnofit-db
    env_file:
      - ./config/.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - storage:/var/lib/mysql
    networks:
      - tecnofit-network

networks:
  tecnofit-network:
    driver: bridge

volumes:
  storage:
    driver: local